### ISSUE TITLE
yo dude this website is so bad

### ISSUE THREAD

**Issue by cory2067** [SamCyanide/mygithubpage#1]

**Comment by SamCyanide** [comment]
merged with issue https://github.com/SamCyanide/mygithubpage/issues/2

**Comment by cory2067** [comment]
here to help with desine, pls consult this consultor of websd design and youw welbsite will jkcreates aesttheicsc byy 493,0% in tje nest fourj ddys guaarrenteed or youjr your mojnery bakc:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;
https://www.linkedin.com/pub/dir/Zhihao/Wang
